version: '3.7'
services:
  db:
    image: mysql:latest
    container_name: mysql-container-new
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: dentalapp
    ports:
      - "3306:3306"
  app:
    build: .
    container_name: dentalapp
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dentalapp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456789
    ports:
      - "8080:8080"
    depends_on:
      - db